export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Nur POST ist erlaubt.' });
  if (!process.env.OPENAI_API_KEY) return res.status(500).json({ error: 'OPENAI_API_KEY fehlt in Vercel.' });
  try {
    const { keywords, level, role, gender, system='5e', setting='Fantasy-Mittelalter', recent=[] } = req.body || {};
    if (!keywords) return res.status(400).json({ error: 'Stichworte fehlen.' });
    const recentText=(Array.isArray(recent)?recent.slice(0,12):[]).map((x,i)=>`${i+1}. Name: ${x?.name||'-'} | Eigenart: ${x?.quirk||'-'} | Geheimnis: ${x?.secret||'-'} | Sprechweise: ${x?.speech||'-'}`).join('\n');
    const schema={type:'object',additionalProperties:false,properties:{
      name:{type:'string'},race:{type:'string'},profession:{type:'string'},age:{type:'integer',minimum:1,maximum:1000},gender:{type:'string'},appearance:{type:'string'},clothing:{type:'string'},personality:{type:'string'},motivation:{type:'string'},quirk:{type:'string'},ideal:{type:'string'},bond:{type:'string'},flaw:{type:'string'},secret:{type:'string'},speech:{type:'string'},skills:{type:'array',minItems:4,maxItems:4,items:{type:'string'}},weaponPrimary:{type:'string',enum:['Keine','Unbewaffnet','Dolch','Knüppel','Handbeil','Kurzschwert','Langschwert','Streitaxt','Kriegshammer','Streitkolben','Kampfstab','Speer','Kurzbogen','Langbogen','Leichte Armbrust','Schwere Armbrust','Schleuder','Messer','Schlagstock','Revolver','Pistole','Gewehr','Schrotflinte','Improvisierte Waffe']},weaponSecondary:{type:'string',enum:['Keine','Unbewaffnet','Dolch','Knüppel','Handbeil','Kurzschwert','Langschwert','Streitaxt','Kriegshammer','Streitkolben','Kampfstab','Speer','Kurzbogen','Langbogen','Leichte Armbrust','Schwere Armbrust','Schleuder','Messer','Schlagstock','Revolver','Pistole','Gewehr','Schrotflinte','Improvisierte Waffe']}
    },required:['name','race','profession','age','gender','appearance','clothing','personality','motivation','quirk','ideal','bond','flaw','secret','speech','skills','weaponPrimary','weaponSecondary']};
    const instructions=`Du erzeugst abwechslungsreiche NSC für einen deutschsprachigen Tabletop-Spielleiter. Das Setting des Nutzers ist verbindlich. Passe Namen, Herkunft/Volk bzw. kulturellen Hintergrund, Beruf, Kleidung, Ausrüstung, Auftreten und gesellschaftlichen Kontext plausibel an Ort, Epoche und Genre an. Verwende keine Fantasy-Elemente, wenn das Setting sie nicht nahelegt. Vermeide Anachronismen: Technik, Mode, Berufe und Gegenstände müssen zeitlich passen. Bei historischen Settings keine modernen Geräte oder moderne Kleidung. Bei Fantasy dürfen passende Fantasy-Völker vorkommen. Schreibe natürliches, konkretes Deutsch, nicht generisch und nicht pathetisch. Respektiere die Stichworte streng. Erfinde keine geschützten Eigennamen aus bekannten Welten. Vermeide Wiederholungen der zuletzt erzeugten Eigenarten, Geheimnisse und Sprechweisen. Erscheinung und Kleidung sollen bildtauglich konkret sein. Wähle genau vier zum Setting und Beruf passende Fertigkeiten als kurze deutsche Begriffe. Wähle außerdem aus den vorgegebenen Waffenlisten eine plausible Hauptwaffe und optional eine Zweitwaffe. Bewaffnung muss zu Setting/Epoche, Volk/Körpergröße, Beruf und Rolle passen. Nicht jeder NSC braucht eine Waffe; Zivilisten dürfen 'Keine' erhalten. Kleine Fantasy-Völker wie Gnome oder Halblinge sollen keine unplausibel großen/schweren Waffen erhalten; Langbogen und Schwere Armbrust vermeiden, Speer nur wenn Beruf/Rolle ihn ausdrücklich nahelegt. Erfinde KEINE Zahlenwerte, Boni oder Regelmechanik; diese berechnet die App.`;
    const input=`Stichworte: ${keywords}\nRegelsystem/Profil: ${system}\nSetting / Welt / Epoche: ${setting}\nErfahrungsstufe: ${level}\nNPC-Typ: ${role}\nGeschlecht: ${gender}\n\nZuletzt erzeugte Elemente, die NICHT wiederholt oder nur umformuliert werden sollen:\n${recentText||'Keine.'}`;
    const apiResponse=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Authorization':`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-5.6-luna',instructions,input,reasoning:{effort:'none'},text:{verbosity:'low',format:{type:'json_schema',name:'npc_profile',strict:true,schema}},max_output_tokens:1400,store:false})});
    const data=await apiResponse.json();if(!apiResponse.ok)return res.status(apiResponse.status).json({error:data?.error?.message||'OpenAI-Textgenerierung fehlgeschlagen.'});
    const text=(data.output||[]).flatMap(item=>item.content||[]).find(part=>part.type==='output_text')?.text;if(!text)return res.status(502).json({error:'OpenAI hat keinen Charaktertext zurückgegeben.'});
    return res.status(200).json(JSON.parse(text));
  } catch(error){return res.status(500).json({error:error?.message||'Unbekannter Serverfehler.'});}
}
